### ISSUE TITLE
The Visitor pods overspawn

### ISSUE THREAD

**Issue by Gleb-Levandovsky** [Vetpetmon-Labs/Wyrms-of-Nyrus-Hub#1]
Hello everyone! I hope that this is correct repository to post this issue :). Yesterday I've caught a very strange bug with "Wyrms of Nyrus" mod.

**A story:**
I watched a showcase of this mod and it interested me very much. I installed it and start my playthrough, everything was OK, no lags, no other strange things. Through some time I reached a day 20 - The Invasion day. I've got killed by Prober very fast, and got to spawn, and then a huge TPS and FPS lags began. On my minimap I saw tons of entities under The Visitor, my entity counter was nearly 2000 and I quickly exited the world.

Then, I created a creative world to test it, started an invasion and this happened:
![2023-07-02_19 01 49](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/assets/138386804/5ce7f727-a4ed-4c4e-9d4a-a5146ff998a9)

https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/assets/138386804/8a6837b0-09ca-462f-854d-d1607cf9bf0f
_Can't upload video longer due to limitations_

**I'm using latest versions of GeckoLib, SynapseLib and Wyrms of Nyrus**

**What was changed:**
**In Wyrms of Nyrus:**
_Preset - "Death World"_
_"Probing" - Disabled_ - Probers were just obliterating my Lycanites pet, and they are were just too strong for 2nd weakest mob in the mod :)
_"Read my modpack" - Disabled_ (and that option with mods and values too, in config it called "uwu" :) )
Last option just make mobs overwhelmingly strong and tanky.

_Mob caps in Universal Tweaks and SR: Parasites set to 60_

I've read the "Incompatible mods" tab in the site, and aware of the possible consequences, but my Lycanites mobs mod don't even close gets to mob cap.

**My mods list:**
[Mod List 2.txt](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/files/11930116/Mod.List.2.txt)
_All of the mods was carefully configured to avoid issues and made gameplay better and I trying to keep them up-to-date._
As it seems to me, in logs there are no errors related to Wyrms of Nyrus mod. I can upload log if you need to.

Very need your help, can I solve this issue? Don't judge me harshly if I forgot something. Thanks :)

**Comment by Vetpetmon** [comment]
Cerberus can't find the .DRM file that it should've generated upon clicking the rightmost button to proceed, did you delete the file or is the game sandboxed? It should create the .DRM file regardless in the instance folder on Linux, or Appdata on Windows. No idea what the behavior is on Mac OS.

The only possible case where this is intended is when Cerberus and it's GUI is removed- Oh. Will hotfix ASAP.

Current workaround is to downgrade to 0.3.41

**Comment by Vetpetmon** [comment]
Attempting to reproduce the issue now.

**Comment by Vetpetmon** [comment]
Failed to reproduce this on my machine. Can you check for a file that looks like this in your instance folder or appdata folder?
![image](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/assets/10699805/22cfda08-30e2-4fef-9179-71df6a2bf144)

I'm thinking this may be both a launcher and OS issue. Or, something outside of Minecraft, Java, and the Launcher had entirely blocked the creation of this file.

**Comment by Gleb-Levandovsky** [comment]
**Hello!**
**I'm using Windows**, I should have said so right away. I made a search both in Appdata/Roaming and Minecraft folder (it is on other HDD), but couldn't find anywhere any files with .DRM extension. Search by name "won" doesn't gave any results too :(
Don't remember deleting this file, but it's still possible, maybe I just didn't attach any importance to it someday...

**Downgrading to 0.3.41 did not bring results.**
So, if I understood correctly, do you mean the button that appears when you doing first launch the game with this mod? Starting from this, I did the following:
1) Removed the "wyrmsofnyrus" config folder
2) Removed the "Wyrms of Nyrus client" config file
3) Downloaded from Modrinth latest version of the mod (0.3.43)
4) Got the message of first mod launch, clicked OK
5) No files neither in appdata/roaming nor in the Minecraft folder called "won" appeared :(
6) The problem continues to manifest itself, which was very predictable after the previous paragraph

Also, I would like to emphasize. I didn't delete the configs after updating from 0.3.41 to 0.3.42 before the issue appeared, but after current tests it doesn't make sense.

It doesn't seems to Launcher of OS somehow limited the ability to create files. I even forcibly unchecked "read only" for the entire folder again before the test. Other mods easily create their configs, editing them and doing the same in root Minecraft folder. Botania, HEI, Optifine, JourneyMap and Aroma Backup are proof of this.

I have Windows own guard, not the other antivirus, and it doesn't give me any warnings about blocking files (in MC folder 100%)

Are you sure, that this is not the mod conflict?

P.S. Issues link on Modrinth page sends you to deleted github page

**Comment by Vetpetmon** [comment]
On Windows, which is what you are using, if the launcher does not redirect the mod to a different location, should place the file around here: 
![image](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/assets/10699805/a06d29b6-119b-4e99-a119-f9291dede731)

What launcher and java version is in use? Usually, the DRM file is put into appdata to avoid having to see the startup message multiple times, though on Linux (Ubuntu), launchers like Prism will put it directly in the instance's root folder instead, so the DRM file does get made per-instance and the startup message gets shown again for new instances regardless.

I cannot seem to replicate this issue on Windows 10, Oracle `JRE 1.8.0_332`. This issue could not be replicated on Ubuntu 22.04 Oracle JRE `1.8.0_35x` and `1.8.0_36x`, along with OpenJDK 8.

I have no way of testing on Windows 11 or legacy windows versions, and Windows Defender has a number of options that may cause issues with writing and reading from the appdata location. WD has this option that can cause problems with file I/O in general:

![image](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/assets/10699805/bc0424b3-e6bb-4bb4-9733-c970113ff7b2)

**NOTICE: If you choose to turn this off to test if this may be the problem, make sure to turn it back on later if you don't work with software like art programs and IDEs!**

I'll see about creating a failsafe just in case, but if your log is not reporting any I/O error(s), then something very wrong happened on your end device and we may not be able to find what exactly caused the issue.

**Comment by Vetpetmon** [comment]
Update: I have notified the Discord & Vetpetmon Labs that this is now a top-priority issue, hopefully more eyes on this will find more details and speed up work towards a patch.

**Comment by Gleb-Levandovsky** [comment]
**Hello again!** Currently I'm using **Windows 11 Ver. 21H2, Build 22000.2057** with **jre1.8.0_341** and **jdk1.8.0_232** if that makes sense.

The "Controlled folder access" option was already disabled for me, maybe because I'm using IntelliJ IDEA and Adobe series soft etc.

**A funny story:**
All of the tests before I did on my modpack with 166 mods (including WON), but after your latest message I was sad and decided to do another test, so:

1) I copied Wyrms of Nyrus mod along with SynapseLib  and GeckoLib to my first modpack, with only Thaumcraft, IC2, Pam's HC, BuildCraft, Heart Drops, Twilight Forest, TA: Reconstructed and Aroma Backup, because I'm too lazy to create new Minecraft instance.
2) Launched the game, I **did not** get the message of the first launch, even when there was no configs related to this mod, but I got a warning, that I get mod not from Modrinth (how did he know, that I copied it?)
3) Started a new world, and there was no issues. **Everything works fine. Visitor spawn 3 pods in around 10 seconds.**

What we need to do next? :)

**Comment by Gleb-Levandovsky** [comment]
**Good afternoon!** Something has changed...

I do not know exactly, but it seems after previous test something has changed. Trying to find out more about the issue, I went into the logs again...

Currently, I'm playing my modpack with 165 mods and Wyrms of Nyrus (set to invade only Twilight Forest). And, **maybe**, it appeared after the test, but, in logs I found the following inscription:

[18:35:41] [Client thread/INFO]: C:\Users\Gleb\AppData\Roaming\WoN.DRM
[18:35:41] [Client thread/INFO]: OBJLoader: Domain wyrmsofnyrus has been added.

I quickly made a search in that folder, and yes, the file appeared. I have to make another test.

**Now I am in my main modpack.** I forced visit and it seems to be OK. Everything works as intended :). I don't know what happened here, but it works!
But, now I have a question: if I faced with a problem, and want to send my modpack to a friend, can the issue happen again?

**Comment by Vetpetmon** [comment]
Seems like an inconsistency between Cerberus, Java's file creation library, and unknown processes, plus development environments, which can be hard to nail the right development conditions for everything. (Trust me, for some reason, indev 0.4 breaks purely because mods like HBM, Betweenlands, and Twilight Forest are not safe for a debug-enabled environment!)

> But, now I have a question: if I faced with a problem, and want to send my modpack to a friend, can the issue happen again?

It should not happen again, since the file should automatically generate on systems that never played with WoN before. The menu that pops up just before the main menu is warning you that WoN has had a serious history of being **illegally redistributed** with malware bundled into it **by unauthorized vendors**. It's a general notice warning you to double-check if you got it from Modrinth, GitHub (For developers), and/or the SNAZ OS Hub. It is to enhance player awareness about the serious risk posed by download mods from weird places like 9minecraft.

I would use File Director to download the mod from Modrinth instead of distributing through a compressed archive file (License forbids this unless if you have explicit permission!) as Modrinth is a secure platform and vets releases from time to time to maintain trust & safety with your players!

For now, this issue will stay open for the next 6 months as this fluke (not 100% reproducible, yet possible to run into the issue) could crop up in the future.

# FOR TESTING:
- Cerberus needs more testing on dedicated *Linux* environments.
- Make sure that dedicated servers on ANY platform that, if they don't make the .DRM file, don't activate Cerberus.

**Comment by Gleb-Levandovsky** [comment]
Hello! Thank you for your work and patience!
If I somehow manage to get more information or the problem will repeat, then I will inform. **Have a good day!**

**Comment by Vetpetmon** [comment]
Problem has been solved as of 0.5.100 with an improvement to the invasion handler that adds failsafes.
