### ISSUE TITLE
crash upon creating a world 

### ISSUE THREAD

**Issue by Thepal117** [Vetpetmon-Labs/Wyrms-of-Nyrus-Hub#3]
[crash-2023-07-05_17.04.13-server.txt](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus-Hub/files/11962976/crash-2023-07-05_17.04.13-server.txt)

**Comment by Vetpetmon** [comment]
HBM is at fault for this, you may want to send it over to the fork's author.
